#!/bin/sh

set -e
fail=0
adjectives=$(cat usr/share/petname/adjectives.txt)
adverbs=$(cat usr/share/petname/adverbs.txt)
names=$(cat usr/share/petname/names.txt)

succeed() {
	echo "⤷ Success"
}

fail() {
	echo "⤷ Failure"
	exit 1
}

echo "TEST: Ensure we have no blacklisted words or derivatives..."
grep -xi -Ff debian/blacklist.txt usr/share/petname/*txt && fail || succeed

echo "TEST: Ensure that we only have a-z in our words; no funny characters; no upper case..."
grep "[^abcdefghijklmnopqrstuvwxyz]" usr/share/petname/*txt && fail || succeed

echo "TEST: Ensure that we have no words more than 12 characters..."
grep "[a-z]\{13\}" usr/share/petname/*txt && fail || succeed

echo "TEST: Ensure we have no repeated words..."
grep -xi -Ff usr/share/petname/adjectives.txt usr/share/petname/adverbs.txt && fail || succeed
grep -xi -Ff usr/share/petname/adjectives.txt usr/share/petname/names.txt && fail || succeed
grep -xi -Ff usr/share/petname/names.txt usr/share/petname/adverbs.txt && fail || succeed

echo "TEST: Ensure that all adverbs end in -ly..."
grep -v "ly$" usr/share/petname/adverbs.txt && fail || succeed

echo "TEST: Ensure that we have no words more than 4 syllables..."
output=$(cat usr/share/petname/*txt | perl -e 'use strict; use Lingua::EN::Syllable; while(<>) { chomp; print $_ . "\n" if syllable($_) > 4; };')
if [ -n "$output" ]; then
	echo "$output"
	fail
else
	succeed
fi

echo "TEST: Ensure all adverbs and adjectives are in the ispell(1) dictionary..."
for word in $adverbs $adjectives; do
	if (echo "$word" | ispell | grep -qs "^word: ok"); then
		continue
	else
		echo $word
		fail=1
	fi
done
[ "$fail" = "1" ] && fail || succeed

echo "TEST: Ensure all adverbs are actually adverbs in the dict(1) dictionary..."
for word in $adverbs; do
	if dict -h localhost "$word" 2>&1 | egrep -qs "^      adv | adv\."; then
		continue
	else
		echo $word
		fail=1
	fi
done
[ "$fail" = "1" ] && fail || succeed

echo "TEST: Ensure all adjectives are actually adjectives in the dict(1) dictionary..."
for word in $adjectives; do
	if dict -h localhost "$word" 2>&1 | egrep -qs "^      adj | adj\."; then
		continue
	elif echo "$word" | egrep -qs "ing$|ed$"; then
		continue
	else
		echo $word
		fail=1
	fi
done
[ "$fail" = "1" ] && fail || succeed

echo "TEST: Ensure all adverbs and adjectives are common in the SCOWL database..."
for word in $adjectives $adverbs; do
	if grep -qsri "^$word$" /usr/share/dict/scowl/english-words.[0-5]?; then
		continue
	else
		echo $word
		fail=1
	fi
done
[ "$fail" = "1" ] && fail || succeed

echo "TEST: Ensure that all names are common nouns in the dictionary..."
for word in $names; do
	fail=0
	if grep -qs "^$word$" debian/whitelist.txt; then
		continue
	fi
	if ! (echo "$word" | ispell | grep -qs "^word: ok"); then
		fail=$((fail+1))
	fi
	if ! (dict -h localhost "$word" 2>&1 | egrep -qs "^      n | n\.|\\n\.") ; then
		fail=$((fail+1))
	fi
	if ! grep -qsri "^$word$" /usr/share/dict/scowl/english-words.[0-7]?; then
		fail=$((fail+1))
	fi
	[ $fail -gt 1 ] && echo $word
done
if [ "$fail" = "1" ]; then
	fail
else
	succeed
fi
